<a href="https://colab.research.google.com/github/Karina0162003/MLP_Programs/blob/main/kneb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as  plt
import seaborn as sns

In [4]:
df = sns.load_dataset('iris')
df.tail(5)

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [6]:
x = df[['sepal_length','sepal_width','petal_length','petal_width']].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = df[['species']].values
y

array([['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['setosa'],
       ['versicolor'],
       ['versicolor'],
    

In [9]:
from sklearn.preprocessing import LabelEncoder
label_y = LabelEncoder()
label_y

LabelEncoder()

In [11]:
y = label_y.fit_transform(y)
np.sort(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
x_train

array([[6.3, 3.3, 4.7, 1.6],
       [6. , 3. , 4.8, 1.8],
       [4.4, 3.2, 1.3, 0.2],
       [5.8, 2.7, 3.9, 1.2],
       [5.6, 2.7, 4.2, 1.3],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.3, 4. , 1.3],
       [5.8, 2.7, 4.1, 1. ],
       [6.1, 3. , 4.9, 1.8],
       [6.9, 3.1, 5.1, 2.3],
       [5.5, 2.5, 4. , 1.3],
       [6.4, 2.8, 5.6, 2.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 2.5, 5.8, 1.8],
       [6.9, 3.1, 4.9, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [7.9, 3.8, 6.4, 2. ],
       [5.8, 4. , 1.2, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [6. , 2.2, 4. , 1. ],
       [6.3, 2.3, 4.4, 1.3],
       [6.6, 2.9, 4.6, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.2, 4.1, 1.5, 0.1],
       [6.3, 2.9, 5.6, 1.8],
       [4.8, 3. , 1.4, 0.3],
       [5.8, 2.7, 5.1, 1.9],
       [5.1, 3.3, 1.7, 0.5],
       [6.4, 2.8, 5.6, 2.2],
       [4.9, 3.1, 1.5, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.7, 3.2, 1.6, 0.2],
       [6.7, 3

In [18]:
from sklearn.neighbors import KNeighborsClassifier
cn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
cn.fit(x_train,y_train)

KNeighborsClassifier()

In [21]:
y_pred = cn.predict(x_test)
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[18,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 13]])

In [24]:
accuracy_score(y_test,y_pred)

0.9777777777777777

In [25]:
cn.score(x_test,y_test)

0.9777777777777777