<a href="https://colab.research.google.com/github/Karina0162003/MLP_Programs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#create array
arr1 = np.array([10,20,30])
arr1

array([10, 20, 30])

In [ ]:
#check the type for array1
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
#check array dimension
print(arr1.ndim)

1


In [ ]:
arr2=np.array([[101,102,103,],[104,105,106,],]) #create the two dimension array
print(arr2) #print the array
print(type(arr2)) #check size of array
print(arr2.dtype) #check the datatype for array
print(arr2.itemsize) #check the array for item-size
print(arr2.shape) #show the shape of arr2

[[101 102 103]
 [104 105 106]]
<class 'numpy.ndarray'>
int64
8
(2, 3)


In [ ]:
arr3=np.array([1,2,3,4,5,6,7,8,9]) #create array3
print(arr3)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr4=arr3.reshape(3,3) #create 3 by 3 matrix using reshape
print(arr4) #print the matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Divide into 5 parts using linspace
arr5=np.linspace(1,3,5)
print(arr5)

[1.  1.5 2.  2.5 3. ]


In [ ]:
#Create 3 by 3 matrix with all zeros using zeros function
arr6=np.zeros((3,3))
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Create 3 by 5 matrix with all ones using ones function
arr7=np.ones((3,5))
print(arr7)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#arange - store 0 to 9 value into arr8
arr8=np.arange(9)
print(arr8)

[0 1 2 3 4 5 6 7 8]


In [ ]:
#Convert into 3 by 3 matrix for arr9
arr9=arr8.reshape(3,3)
print(arr9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Store 13 to 19 values into array
arr10=np.arange(13,19) #list argument is for start value and 2nd for the end value
print(arr10)

[13 14 15 16 17 18]


In [ ]:
#Store 13 to 19 values into array
arr10=np.arange(13,19,3) #list argument is for start value and 2nd for the end value and third for the skip value
print(arr10)

[13 16]


In [ ]:
print(arr10[:]) #slicing for array10

[13 16]


In [ ]:
arr12=np.arange(9).reshape(3,3)
print(arr12)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
arr13=np.arange(9).reshape(3,3)
print(arr13)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Convert 2 matrix into vertically
arr14=np.vstack((arr12,arr13))
arr14

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Convert 2 matrix into horizontally
arr15=np.hstack((arr12,arr13))
arr15

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [ ]:
#split the matrix into 2 row 5 column for horizontally
arr16=np.hsplit(arr12,(2,5))
arr16

[array([[0, 1],
        [3, 4],
        [6, 7]]),
 array([[2],
        [5],
        [8]]),
 array([], shape=(3, 0), dtype=int64)]

In [ ]:
#split the matrix into 2 row 5 column for vertically
arr17=np.vsplit(arr12,(2,5))
arr17

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([], shape=(0, 3), dtype=int64)]

In [ ]:
print(arr12)
print("after spliting! data")
arr18=np.vsplit(arr12,(2,6))
arr18

[[0 1 2]
 [3 4 5]
 [6 7 8]]
after spliting! data


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([], shape=(0, 3), dtype=int64)]

In [ ]:
arr19=np.array([1,2,3,4,5,6]).reshape(2,3)
print(arr19)
arr20=np.transpose(arr19) #Convert row value into column value
print(arr20)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr21=np.array([10,20,30,40,50])
print(arr21)
arr22=np.array([60,70,80,90,100])
print(arr22)


[10 20 30 40 50]
[ 60  70  80  90 100]


In [ ]:
arr_sum= np.add(arr21,arr22) #addition
print(arr_sum)

[ 70  90 110 130 150]


In [ ]:
arr_sub= np.subtract(arr21,arr22) #subtract
print(arr_sub)

[-50 -50 -50 -50 -50]
