<a href="https://colab.research.google.com/github/Karina0162003/MLP_Programs/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.reshape(b,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.reshape(a,(1,3))

array([[1, 2, 3]])

In [23]:
c=np.array([1,2,3,4,4,5,6,7,8]).reshape(3,3)
c

array([[1, 2, 3],
       [4, 4, 5],
       [6, 7, 8]])

In [29]:
d=np.array(range(1,10))
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
print(np.ndim(d))
print(c.itemsize)
print(np.size(b))
print(type(a))
print(a.dtype)
print(a.shape)

1
8
9
<class 'numpy.ndarray'>
int64
(3,)


In [48]:
a1 = np.arange(1,10).reshape((3,3))
a2 = np.arange(11,20).reshape((3,3))
a1
a2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [49]:
np.vstack(a1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.hstack(a2)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [56]:
np.hsplit(a1,(2,3))

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]]),
 array([], shape=(3, 0), dtype=int64)]

In [57]:
np.vsplit(a2,(3,2))

[array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]),
 array([], shape=(0, 3), dtype=int64),
 array([[17, 18, 19]])]

In [58]:
np.add(a1,a2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [60]:
np.subtract(a1,a2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [61]:
np.mod(a1,a2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.mean(a1)

5.0

In [65]:
np.power(a1,a2)

array([[                  1,                4096,             1594323],
       [          268435456,         30517578125,       2821109907456],
       [    232630513987207,   18014398509481984, 1350851717672992089]])

In [69]:
np.divide(a1,a2)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [72]:
np.std(a1)

2.581988897471611

In [75]:
np.shape(a1)

(3, 3)

In [76]:
np.abs(a1,a2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.multiply(a1,a2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [78]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.linspace(1,10,3,6)

array([ 1. ,  5.5, 10. ])

In [96]:
np.random.random((1,10))

array([[0.46356284, 0.1107127 , 0.27201224, 0.07295167, 0.69411005,
        0.51424328, 0.32117482, 0.5594614 , 0.82347097, 0.42884798]])

In [97]:
np.random.randint((1,10))

array([0, 9])

In [99]:
np.random.rand(1,10)

array([[0.92854277, 0.4988364 , 0.5203154 , 0.19503446, 0.36605042,
        0.93475237, 0.68338122, 0.70059854, 0.19794113, 0.02771792]])

In [105]:
np.random.randint(0,10,(3,3))

array([[8, 6, 2],
       [9, 6, 1],
       [9, 6, 0]])

In [111]:
s=np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
type(s)

numpy.ndarray

In [114]:
q=np.arange(1,10)*5
q

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [115]:
np.std(q)

12.909944487358056

In [116]:
l1=[1,2,3,4,5,6]
np.array(l1)

array([1, 2, 3, 4, 5, 6])

In [118]:
np.max(l1)

6

In [119]:
np.min(l1)

1

In [122]:
p=np.arange(1,26).reshape((5,5))
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
np.size(p)

25

In [124]:
np.shape(p)

(5, 5)

In [127]:
k=np.random.randint(1,10)

In [131]:
np.mean(k)

5.0

In [133]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [134]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [136]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [137]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [139]:
np.sum(a1)

45

In [140]:
np.min(a1)

1

In [141]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])